version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    container_name: toman-backend-app
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GATEWAY_API_BASE_URL: ${NEXT_PUBLIC_GATEWAY_API_BASE_URL}
    environment:
      NEXT_PUBLIC_GATEWAY_API_BASE_URL: ${NEXT_PUBLIC_GATEWAY_API_BASE_URL}
    ports:
      - "4000:3000"
    container_name: toman-frontend-app
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
